---

- name: install nginx.repo
  template:
    src: nginx.repo.j2
    dest: /etc/yum.repos.d/nginx.repo
  tags: nginx

- name: install nginx
  yum:
    name: nginx
    state: latest
  tags: nginx

- name: nginx init script
  copy:
    src: nginx.init
    dest: /etc/init.d/nginx
    mode: 0755
  tags: nginx

- name: make conf.d
  file:
    dest: /etc/nginx/conf.d
    state: directory
  tags: nginx

- name: nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx
  tags: nginx
