---

- name: install nginx.repo
  file: src=nginx.conf dest=/etc/yum.repos.d/nginx.repo

- name: install nginx
  yum: name=nginx state=latest

- name: make conf.d
  file:
    dest=/etc/nginx/conf.d
    state=directory
