---

- include: install.yml

- name: nginx "{{ name }}" conf.d
  template:
    src: "{{ name }}.conf.j2"
    dest: "/etc/nginx/conf.d/{{ name }}.conf"
  notify:
    - restart nginx

- name: remove default.conf
  file:
    dest: /etc/nginx/conf.d/default.conf
    state: absent
  notify:
    - restart nginx
