---

- name: install easy_install
  yum:
    name: python-setuptools
    state: present

- name: install pip
  easy_install:
    name: pip

- name: install python-devel
  yum:
    name: python-devel
    state: latest

- name: install initscripts
  yum:
    name: initscripts
    state: latest

- name: install epel
  yum:
    name: "http://download.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
