---

- name: install easy_install
  yum: name=python-setuptools state=present

- name: install pip
  easy_install: name=pip state=present

- name: install python-devel
  yum: name=python-devel state=latest

- name: install nginx.repo
  file: src=nginx.conf dest=/etc/yum.repos.d/nginx.repo

