---

- name: install easy_install
  yum:
    name: python-setuptools
    state: present

- name: install pip
  easy_install:
    name: pip

- name: install initscripts
  yum:
    name: initscripts state=latest
