---

- name: install epel
  tags: common
  yum:
    name: "http://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present

- name: install base RPMs
  tags: common
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - htop
    - initscripts
    - net-tools
    - python-setuptools
    - python-devel
    - sysstat
    - vim-enhanced

- name: install pip
  tags: common
  easy_install:
    name: pip
