---

- name: install whisper, carbon, and graphite-web
  tags: graphite
  pip: 
    name: "{{ item }}"
    state: present
  with_items:
    - whisper
    - carbon
    - graphite-web
    - pytz
  
- name: install graphite-web python dependencies
  tags: graphite
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - django
    - django-tagging

- name: install graphite-web rpm dependencies
  tags: graphite
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - fontconfig
    - pycairo

- name: graphite syncdb
  tags: graphite
  command: python manage.py syncdb --noinput
  args:
    chdir: /opt/graphite/webapp/graphite
    creates: /opt/graphite/storage/graphite.db
