---

- include: install.yml

- name: carbon-cache init script
  tags: graphite
  copy:
    src: carbon-cache.init
    dest: /etc/init.d/carbon-cache
    mode: 0755

- name: configure carbon.conf
  tags: graphite
  template: 
    src: carbon.conf.j2
    dest: /opt/graphite/conf/carbon.conf

- name: configure carbon storage-schemas
  tags: graphite
  template: 
    src: storage-schemas.conf.j2
    dest: /opt/graphite/conf/storage-schemas.conf

- name: configure graphite local_settings.py
  tags: graphite
  template:
    src: local_settings.py.j2
    dest: /opt/graphite/webapp/graphite/local_settings.py
