---

- name: install whisper
  pip: 
    name=whisper
    state=present
  
- name: install carbon
  pip:
    name=carbon
    state=present

- name: install graphite-web
  pip: 
    name=graphite-web
    state=present

- name: install graphite-web python dependencies
  pip:
    name={{ item }}
    state=present
  with_items:
    - gunicorn
    - django
    - django-tagging

- name: install graphite-web rpm dependencies
  yum:
    name={{ item }}
    state=present
  with_items:
    - fontconfig
    - pycairo
 
- name: carbon-cache init script
  copy:
    src=carbon-cache.init
    dest=/etc/init.d/carbon-cache
    mode=0755

- name: configure carbon.conf
  template: 
    src=carbon.conf.j2
    dest=/opt/graphite/conf/carbon.conf

- name: configure carbon storage-schemas
  template: 
    src=storage-schemas.conf.j2
    dest=/opt/graphite/conf/storage-schemas.conf

- name: configure graphite-web wsgi
  file: 
    src=graphite.wsgi
    dest=/opt/graphite/conf/graphite.wsgi

- name: configure graphite local_settings.py
  template:
    src=local_settings.py.j2
    dest=/opt/graphite/webapp/graphite/local_settings.py

- name: enable and start carbon-cache
  service:
    name=carbon-cache
    enabled=yes
    state=started
