---
- name: restart monit
  service:
    name: monit
    state: restarted
  when: ansible_virtualization_type != "docker"

- name: reload monit
  service:
    name: monit
    state: reloaded
  when: ansible_virtualization_type != "docker"
