---

nginx:
  keepalive_timeout: 65
  core:
    default_type: "application/octet-stream"
    sendfile: "on"
    tcp_nodelay: "on"
    worker_processes: 1
    worker_connections: 1024
  gzip: "off"

tls:
  ciphers:
    enabled:
      - ECDHE-RSA-AES256-GCM-SHA384
      - ECDHE-RSA-AES256-GCM-SHA
      - ECDHE-RSA-AES256-SHA384
      - ECDHE-RSA-AES256-SHA
      - ECDHE+AESGCM
      - DHE+AESGCM
      - AES256+EECDH
      - AES256+EDH
      - ECDHE-ECDSA-AES128-GCM-SHA256 # Java 8
      - ECDHE-ECDSA-AES128-SHA256     # Java 8
      - DHE-RSA-AES128-SHA            # Java 7
    disabled:
      - aNULL
      - eNULL
      - EXPORT
      - DES
      - MD5
      - PSK
      - RC
  force_android_2_3: DHE-RSA-AES128-GCM-SHA256
 
repo:
  old: false 
