---

nginx:
  keepalive_timeout: 65
  core:
    default_type: "application/octet-stream"
    sendfile: "on"
    tcp_nodelay: "on"
    worker_processes: 1
    worker_connections: 1024
  gzip: "off"
   
repo:
  old: false 
