---
resources:

- name: lab-repo
  type: git
  icon: github
  source:
    uri: https://github.com/mschenck/lab.git
    branch: main
    username: ((gh_user))
    password: ((gh_pat))
    paths:
    - src/services/introspectd/*.go
    - src/services/introspectd/Dockerfile
    - src/services/introspectd/README.md

- name: semver
  type: semver
  icon: github
  source:
    driver: git
    uri: https://((gh_user)):((gh_pat))@github.com/mschenck/lab.git
    branch: main
    file: src/services/introspectd/version
    commit_message: "semver updating %file% to %version%"
    git_user: "git@github.com"

- name: introspectd-image
  type: registry-image
  icon: docker
  source:
    repository: ghcr.io/mschenck/introspectd
    username: ((gh_user))
    password: ((gh_pat))
    tag: latest
    debug: true

jobs:
  - name: build-introspectd
    plan:
      - get: lab-repo
        trigger: true

      - get: semver
        params:
          bump: minor
          outputs:
            - name: version

      - task: build-container-image
        privileged: true
        config:
          platform: linux

          image_resource:
            type: registry-image
            source: 
              repository: concourse/oci-build-task
          
          caches:
            - path: cache

          inputs:
            - name: lab-repo
          outputs:
            - name: image

          params:
            CONTEXT: lab-repo/src/services/introspectd
            OUTPUT_OCI: true

          run:
            path: build

      - put: semver
        params:
          file: semver/version

      - put: introspectd-image
        inputs: detect
        params:
          image: image/image.tar
          additional_tags: semver/version
        get_params:
          skip_download: true