---
resources:

- name: lab-repo
  type: git
  icon: github
  source:
    uri: git@github.com:mschenck/lab.git
    branch: main
    username: ((gh_user))
    password: ((gh_pat))
    file: 

- name: version
  type: semver
  icon: github
  source:
    driver: git
    uri: git@github.com:mschenck/lab.git
    branch: main
    file: services/introspectd/version
    username: ((gh_user))
    password: ((gh_pat))

- name: introspectd-image
  type: registry-image
  icon: docker
  source:
    repository: ghcr.io/mschenck/introspectd
    username: ((gh_user))
    password: ((gh_pat))
    debug: true

jobs:
  - name: build-introspectd
    plan:
      - get: lab-repo
        trigger: true

      - put: version
        params:
          get_latest: true
          bump: minor

      - task: build-container-image
        privileged: true
        config:
          platform: linux

          image_resource:
            type: registry-image
            source: 
              repository: concourse/oci-build-task
          
          caches:
            - path: cache

          inputs:
            - name: lab-repo
          outputs:
            - name: image

          params:
            CONTEXT: lab-repo/services/introspectd
            OUTPUT_OCI: true

          run:
            path: build

      - put: version
        params: {file: version/version}

      - put: introspectd-image
        inputs: detect
        params:
          image: image/image.tar
          additional_tags: lab-repo/services/introspectd/version
        get_params:
          skip_download: true