---

- name: install docker YUM repo
  copy:
    src: docker.repo
    dest: /etc/yum.repos.d/docker.repo
    mode: 0644

- name: install docker
  tags: docker
  yum:
    name: docker-engine
    state: present

- name: load "overlay" kernel module when using overlyfs storage
  tags: docker
  modprobe:
    name: overlay
    state: present
  when: ansible_virtualization_role == "host"
