---

- include: install.yml

- name: sysconfig docker
  tags: docker
  template:
    src: sysconfig/docker.j2
    dest: /etc/sysconfig/docker

- name: sysconfig docker-storage
  tags: docker
  template:
    src: sysconfig/docker-storage.j2
    dest: /etc/sysconfig/docker-storage

- name: start/enable docker service
  tags: docker
  service:
    name: docker
    state: started
    enabled: yes
