---

- name: install libselinux-python
  tags: docker
  yum:
    name: libselinux-python
    state: present

- name: set SELinux state
  tags: common
  selinux:
    policy: "{{ selinux_policy }}"
    state: "{{ selinux_state }}"
