---

# Graphite node

- hosts: all
  roles:
    - common
    - graphite
    - { role: gunicorn,
        name: graphite,
        app_root: /opt/graphite/webapp }
    - { role: monit,
        name: graphite,
        pidfile: /var/run/graphite.pid }
