---

# Lab node

- hosts: labnodes

  vars:

    docker_storage_driver: devicemapper

    # Docker STORAGE_DRIVER set to "overlay" is incompatible with SELinux
    selinux_state: permissive

  roles:

    # common
    - {
        role: common,
      }

    # docker
    - {
        role: docker,
        selinux_state: "{{ selinux_state }}",
        docker_storage_driver: "{{ docker_storage_driver }}",
      }
