---

- include: install.yml

- name: gunicorn "{{ name }}" wsgi
  template:
    src: "{{ name }}.wsgi.j2"
    dest: "{{ app_root }}/{{ name }}/{{ name }}_wsgi.py"

- name: install "{{ name }}" init
  template:
    src: "gunicorn.init.j2"
    dest: "/etc/init.d/{{ name }}"
    mode: 0755
  notify: restart "{{ name }}"
