apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcpecho-auto
  labels:
    app: tcpecho-auto
spec:
  selector:
    matchLabels:
      app: tcpecho-auto
  replicas: 3
  template:
    metadata:
      labels:
        app: tcpecho-auto
    spec:
      containers:
      - name: tcpecho-auto
        image: 601467590780.dkr.ecr.us-east-1.amazonaws.com/tcpecho:latest
        ports:
        - containerPort: 1337
        env:
          - name: PROXY_PROTO
            value: "auto"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcpecho-proxy
  labels:
    app: tcpecho-proxy
spec:
  selector:
    matchLabels:
      app: tcpecho-proxy
  replicas: 3
  template:
    metadata:
      labels:
        app: tcpecho-proxy
    spec:
      containers:
      - name: tcpecho-proxy
        image: 601467590780.dkr.ecr.us-east-1.amazonaws.com/tcpecho:latest
        ports:
        - containerPort: 1337
        env:
          - name: PROXY_PROTO
            value: "proxy"
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tcpecho-tcp
  labels:
    app: tcpecho-tcp
spec:
  selector:
    matchLabels:
      app: tcpecho-tcp
  replicas: 3
  template:
    metadata:
      labels:
        app: tcpecho-tcp
    spec:
      containers:
      - name: tcpecho-tcp
        image: 601467590780.dkr.ecr.us-east-1.amazonaws.com/tcpecho:latest
        ports:
        - containerPort: 1337
---
apiVersion: v1
kind: Service
metadata:
  name: tcpecho-tcp
  labels:
    app: tcpecho-tcp
spec:
  ports:
  - name: tcpecho-tcp
    port: 1336
    protocol: TCP
    targetPort: 1337
  selector:
    app: tcpecho-tcp
---
apiVersion: v1
kind: Service
metadata:
  name: tcpecho-proxy
  labels:
    app: tcpecho-proxy
spec:
  ports:
  - name: tcpecho-proxy
    port: 1338
    protocol: TCP
    targetPort: 1337
  selector:
    app: tcpecho-proxy
---
apiVersion: v1
kind: Service
metadata:
  name: tcpecho-auto
  labels:
    app: tcpecho-auto
spec:
  ports:
  - name: tcpecho-auto
    port: 1337
    protocol: TCP
    targetPort: 1337
  selector:
    app: tcpecho-auto
